version: '3'

services:
  mariadb:
    init: true
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "3306"
    restart: always
    volumes:
      - db_volumes:/var/lib/mysql
    networks:
      - intra

  wordpress:
    volumes:
      - wp_volumes:/var/www/html/wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    expose:
      - "9000"
    networks:
      - intra

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: requirements/nginx/Dockerfile
  #   volumes:
  #     - /home/changhyl/data:/etc/nginx/conf.d
  #   ports:
  #     - "443:443"
  #   networks:
  #     - intra

networks:
  intra:
    driver: bridge

volumes:
  db_volumes:
    name: db_volumes
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/changhyl/data/db/
  wp_volumes:
    name: wp_volumes
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/changhyl/data/wp/