version: '3'

services:
  mariadb:
    init: true
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "3306"
    restart: on-failure
    volumes:
      - db_volumes:/var/lib/mysql
    networks:
      - docker-network

  wordpress:
    volumes:
      - wp_volumes:/var/www/html/wordpress
    env_file:
      - .env
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - mariadb
    env_file:
      - .env
    expose:
      - "9000"
    networks:
      - docker-network

  nginx:
    env_file:
      - .env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - wp_volumes:/var/www/html/wordpress
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  db_volumes:
    name: db_volumes
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/changhyl/data/db/
  wp_volumes:
    name: wp_volumes
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/changhyl/data/wp/