version: '3'

services:
  mariadb:
    init: true
    build: requirements/mariadb
    env_file:
      - .env
    expose:
      - "3306"
    restart: always
    volumes:
      - dp_vol:/var/lib/mysql
    networks:
      - docker-network

  wordpress:
    volumes:
      - wp_vol:/var/www/html/wordpress
    env_file:
      - .env
    build: requirements/wordpress
    restart: always
    depends_on:
      - mariadb
    expose:
      - "9000"
    networks:
      - docker-network

  nginx:
    env_file:
      - .env
    build: requirements/nginx
    restart: always
    volumes:
      - wp_vol:/var/www/html/wordpress
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  dp_vol:
    name: dp_vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/changhyl/data/db/
  wp_vol:
    name: wp_vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/changhyl/data/wp/
