version: '3'

services:
  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    env_file:
      - .env
    volumes:
      - /home/changhyl/data:/etc/mysql/conf.d
    expose:
      - "3306"
    networks:
      - intra

  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    volumes:
      - /home/changhyl/data:/etc/nginx/conf.d
    ports:
      - "443:443"
    networks:
      - intra

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    depends_on:
      - mariadb
    env_file:
      - .env
    expose:
      - "9000"
    networks:
      - intra

networks:
  intra:
    driver: bridge
